on: [push]

jobs:
  build:
    name: Hook
    runs-on: ubuntu-latest
    steps:
    - name: Hook
      uses: jasongitmail/fast-webhook@v1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        json: '{"path":"/var/www/zhaoweiguo.com/www.zhaoweiguo.com", "branch": "master", "actions": ["pull"]}'





